export const eventsConfig = [
    {
        id: 106,
        eventDay: '13-22 июня',
        eventInfoDate: '13-22 июня',
        eventInfoTitle: 'КУЛЬТЛЕТО',
        eventDescription: 'КУЛЬТЛЕТО В ДК "ЮБИЛЕЙНОМ" Весна подходит к концу, дети и взрослые с нетерпением ждут начала лета и каникул. Для детей и подростков в Краснопахорском доме культуры подготовили творческие интенсивы. Предлагаем вам ознакомиться с программой летних творческих занятий, запланированных в ДК "Звёздный" и его структурном подразделении в селе Былово - ДК "Юбилейный".Справки по телефонам: +7 926 499-30-32, +7 916 359-64-90',
        eventCost: 'ДК Юбилейный',
        eventImgSrc: require('../../assets/images/eventsImages/kultleto-b-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/kultleto-b-02.jpg'),
    },
    {
        id: 105,
        eventDay: '13-22 июня',
        eventInfoDate: '13-22 июня',
        eventInfoTitle: 'КУЛЬТЛЕТО',
        eventDescription: 'КУЛЬТЛЕТО В ДК "ЗВЁЗДНЫЙ" Весна подходит к концу, дети и взрослые с нетерпением ждут начала лета и каникул. Для детей и подростков в Краснопахорском доме культуры подготовили творческие интенсивы. Предлагаем вам ознакомиться с программой летних творческих занятий, запланированных в ДК "Звёздный" и его структурном подразделении в селе Былово - ДК "Юбилейный".Справки по телефонам: +7 926 499-30-32, +7 916 359-64-90',
        eventCost: 'ДК Звездный',
        eventImgSrc: require('../../assets/images/eventsImages/kultleto-k-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/kultleto-k-02.jpg'),
    },
    {
        id: 104,
        eventDay: '26 июня - 04 авг',
        eventInfoDate: '26 июня - 04 августа',
        eventInfoTitle: 'ЛЕТНЯЯ ТВОРЧЕСКАЯ ЛАБОРАТОРИЯ',
        eventDescription: 'ЛЕТНЯЯ ТВОРЧЕСКАЯ ЛАБОРАТОРИЯ в ДК "ЗВЁЗДНЫЙ" Прямо сейчас вы можете организовать летний  досуг ваших детей!!! Методисты и руководители творческих коллективов Краснопахорского дома культуры подготовили интереснейшие программы с познавательными встречами, играми и мастерскими. Основы английского языка и путешествия по просторам Вселенной, знаменитые даты в истории России или мир рукоделия, - выбирать вам! По этой ссылке вы можете подать заявку. Стоимость участия одного ребёнка составляет 8000 тысяч рублей.',
        eventCost: 'ДК Звездный',
        eventImgSrc: require('../../assets/images/eventsImages/LTL-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/LTL-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'CБ',
        eventDayNumber: '10',
        eventInfoDate: '10 июня',
        eventInfoTitle: 'Троицкие гуляния',
        eventDescription: '10 июня в 12-00 в Парке Победы стостоится 14 состоится межрегиональный духовно-просветительский народный праздник',
        eventCost: 'Парк Победы',
        eventImgSrc: require('../../assets/images/eventsImages/troica-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/troica-02.jpg'),
    },
    {
        id: 102,
        eventDay: 'СБ',
        eventDayNumber: '3',
        eventInfoDate: '3 июня',
        eventInfoTitle: 'Анастасия Раинская с концертом «Как Россия»',
        eventDescription: 'В программе – авторские песни о жизни, любви, России… Тексты Анастасии наполнены смыслом, поэтому заставляют задуматься и находят отклик в сердцах зрителей. Певица своим творчеством вдохновляет людей, пробуждает светлые чувства и заряжает своим позитивом и энергией.',
        eventCost: 'Онлайн билеты по ссылке https://new.biletof.com/action/?frame=1&ra=9842',
        eventImgSrc: require('../../assets/images/eventsImages/AR-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/AR-02.jpg'),
    },
    {
        id: 101,
        eventDay: 'ВС',
        eventDayNumber: '28',
        eventInfoDate: '28 мая',
        eventInfoTitle: 'Фестиваль "Русь великая"',
        eventPlace: 'ДК Звездный',
        eventDescription: '28 МАЯ В 12 ЧАСОВ в поселке Красная Пахра в ДК "Звездный" состоится фестиваль "Содружество" посвященный Дню славянской письменности и культуры ',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/sod-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/sod-02.jpg'),
    },
    {
        id: 101,
        eventDay: 'ПТ',
        eventDayNumber: '26',
        eventInfoDate: '26 мая',
        eventInfoTitle: 'МЕЖДУНАРОДНЫЙ ДЕНЬ СОСЕДЕЙ',
        eventPlace: 'Красная Пахра на площадке у дома 15',
        eventDescription: '26 МАЯ В 16 ЧАСОВ в поселке Красная Пахра на площадке у дома 15 состоится праздник - МЕЖДУНАРОДНЫЙ ДЕНЬ СОСЕДЕЙ. Приходите! Будет весело и интересно! В программе: выступления творческих коллективов, конкурсы, угощения и дружеское общение.',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/sosedi-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/sosedi-02.jpg'),
    },
    {
        id: 100,
        eventDay: 'ВС',
        eventDayNumber: '21',
        eventInfoDate: '16 мая',
        eventInfoTitle: 'ГОЛОСА НОВОЙ МОСКВЫ',
        eventPlace: 'ДК Звездный',
        eventDescription: '21 мая в 12 часов в доме культуры "Звёздный" состоится финал конкурса эстрадного вокала "ГОЛОСА НОВОЙ МОСКВЫ".После отборочного тура, который проходил на краснопахорской сцене в минувшие выходные, члены жюри определили детей и подростков, которые получили приглашение принять участие в гала-концерте.21 мая в ДК "Звёздный" участникам проекта и зрителям предоставится прекрасная возможность познакомиться со специальными гостями творческого праздника:народной артисткой РСФСР Жанной Бичевской и российским поэтом-песенником Александром Шагановым.',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/Golosaaa-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/Golosaaa-02.jpg'),
    },
    {
        id: 99,
        eventDay: 'СБ',
        eventDayNumber: '20',
        eventInfoDate: '20 мая',
        eventInfoTitle: 'Новые приключения Буратино и его друзей',
        eventPlace: 'ДК Юбилейный',
        eventDescription: 'Театр "Арлекин" Приглашает 20 мая в 13 часов в структурном подразделении  ДК "Звёздный" в селе Былово состоится премьера спектакля Елены Матвеевой и театра "Арлекин" "Новые приключения Буратино и его друзей". Режиссёр Елена Матвеева выбрала для постановки произведение "Вторая тайна золотого ключика" соавторов А. Кумма и С. Рунге. В кукольном спектакле зрителей ждёт много впечатляющих и запоминающихся мизансцен, музыки и интересных световых решений. ',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/pin-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/pin-02.jpg'),
    },
    {
        id: 98,
        eventDay: 'СБ',
        eventDayNumber: '20',
        eventInfoDate: '20 мая',
        eventInfoTitle: 'Игротека',
        eventPlace: 'ДК Юбилейный',
        eventDescription: '20 мая в 14-00 в доме культуры села Былово играем в настольные игры: лото, шашки, морской бой',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/igra-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/igra-02.jpg'),
    },
    {
        id: 97,
        eventDay: 'ВТ',
        eventDayNumber: '16',
        eventInfoDate: '16 мая',
        eventInfoTitle: 'Творческая встреча',
        eventPlace: 'ДК Юбилейный',
        eventDescription: '16 мая в 18-00 в доме культуры села Былово художник Алекей Козлов проведет творческую встречу, приуроченный ко Дню рисунка.',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/mkk-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/mkk-02.jpg'),
    },
    {
        id: 96,
        eventDay: 'ВТ',
        eventDayNumber: '16',
        eventInfoDate: '16 мая',
        eventInfoTitle: '"Терроризм сжигает мир!"',
        eventPlace: 'ДК Звездный',
        eventDescription: 'В ДК "Звездный" Методисты краснопахорского дома культуры приглашают подростков поселения на встречу. Беседа состоится сегодня, 16 мая в 17 часов Тема беседы: "Терроризм сжигает мир!"',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/ter-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/ter-02.jpg'),
    },
    {
        id: 95,
        eventDay: 'ПН',
        eventDayNumber: '15',
        eventInfoDate: '15-20 мая',
        eventInfoTitle: 'Выставка',
        eventPlace: 'ДК Юбилейный',
        eventDescription: 'С 15 по 20 мая в селе Былово в ДК "Юбилейный" пройдёт выставка изобразительного искусства когда семья вместе ',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/777-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/777-02.jpg'),
    },
    {
        id: 94,
        eventDay: 'ВС',
        eventDayNumber: '14',
        eventInfoDate: '14 мая',
        eventInfoTitle: 'Конкурс эстрадного вокала "Голоса новой Москвы"',
        eventPlace: 'ДК Звездный',
        eventDescription: '14 мая в 12.00 в ДК "Звёздный" состоится конкурс эстрадного вокала "Голоса новой Москвы"',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/g-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/g-02.jpg'),
    },
    {
        id: 93,
        eventDay: 'СБ',
        eventDayNumber: '13',
        eventInfoDate: '13 мая',
        eventInfoTitle: 'Турнир по фланкировке',
        eventPlace: 'ДК Звездный',
        eventDescription: '13 мая в 10.00 впервые в поселении Краснопахорское на базе ДК "Звёздный" пройдёт турнир по фланкировке казачьей шашкой.Турнир организован по инициативе участников Краснопахорской студии фланкировки казачьей шашкой "ГридинЪ" и её руководителя Анастасии Елесеевой.Турнир проводится при поддержке руководства дома культуры и администрации поселения.Ознакомиться с положением и правилами турнира можно по ссылке.        ',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/flank-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/flank-02.jpg'),
    },
    {
        id: 92,
        eventDay: 'ПТ',
        eventDayNumber: '12',
        eventInfoDate: '12 мая',
        eventInfoTitle: 'Мир мюзикла или прекрасная история любви',
        eventPlace: 'ДК Звездный',
        eventDescription: '12 мая в 18.00 в ДК "Звёздный" состоится открытый прогон "Мир мюзикла или прекрасная история любви" ',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/love-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/love-02.jpg'),
    },
    {
        id: 91,
        eventDay: 'ПН',
        eventDayNumber: '8',
        eventInfoDate: '8 мая',
        eventInfoTitle: 'Встреча в клубе "Сельчанка"',
        eventDescription: 'В структурном подразделении ДК "Юбилейный" в селе Былово пройдёт встреча в клубе "Сельчанка"',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/sel-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/sel-02.jpg'),
    },
    {
        id: 90,
        eventDay: 'ПТ',
        eventDayNumber: '6',
        eventInfoDate: '6 мая',
        eventInfoTitle: 'Открытый фестиваль-конкурс',
        eventDescription: 'Этих дней не смолкнет слава. Коллектив ДК "Звёздный" приглашает всех желающих принять участие в творческом, военно-патриотическом проекте. Это заочный ежегодный фестиваль-конкурс "Этих дней не смолкнет слава". Просим вас ознакомиться с положением о конкурсе. С нетерпением ждём видеозаписи ваших номеров и постановок.',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/9-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/9-02.jpg'),
    },
    {
        id: 89,
        eventDay: 'ЧТ',
        eventDayNumber: '4',
        eventInfoDate: '4 мая',
        eventInfoTitle: 'Выставка',
        eventDescription: 'С 4 по 13 мая в структурном подразделении ДК "Юбилейный" в селе Былово пройдёт выставка творческих работ участников арт-студии. Художник Алексей Козлов и его юные воспитанники подготовили экспозицию, приуроченную ко Дню Победы.',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/v1b-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/v1b-02.jpg'),
    },
    {
        id: 88,
        eventDay: 'ЧТ',
        eventDayNumber: '4',
        eventInfoDate: '4 мая',
        eventInfoTitle: 'Выставка',
        eventDescription: 'С 4 по 10 мая в ДК "Звёздный" пройдёт выставка творческих работ участников арт-студии. Художник Алексей Козлов и его юные воспитанники подготовили экспозицию, приуроченную ко Дню Победы.',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/v2-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/v2-02.jpg'),
    },
    {
        id: 87,
        eventDay: 'ВТ',
        eventDayNumber: '2',
        eventInfoDate: 'с 2 мая по 27 мая',
        eventInfoTitle: 'Мероприятия Краснопахорской библиотеки',
        eventPlace: 'Красная Пахра',
        eventDescription: 'С 2 мая по 27 мая в библиотеке "Красная Пахра" пройдёт серия мероприятий:"нам 41-й не забыть, нам 41-й помнить!","Поле боевой славы", "Этот день мы приближали как могли", "Здесь родины моей начало".',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/k-mai-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/k-mai-02.jpg'),
    },
    {
        id: 86,
        eventDay: 'СР',
        eventDayNumber: '3',
        eventInfoDate: 'с 3 мая по 24 мая',
        eventInfoTitle: 'Мероприятия библиотеки Былово',
        eventPlace: 'ДК Юбилейный',
        eventDescription: 'С 3 мая по 24 мая в библиотеке "Былово" пройдёт серия мероприятий:"И снова май!Салют!Победа!","Сказочник с мольбертом", "Письма с фронта", "Отказ от вредных веществ-путь к здоровой жизни".',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/b-mai-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/b-mai-02.jpg'),
    },
    {
        id: 85,
        eventDay: 'СР',
        eventDayNumber: '3',
        eventInfoDate: 'с 3 мая по 24 мая',
        eventInfoTitle: 'Мероприятия библиотеки Минзаг',
        eventPlace: 'Минзаг',
        eventDescription: 'С 3 мая по 24 мая в библиотеке "Минзаг" пройдёт серия мероприятий:"Бесмертный полк","Талантливый писатель", "Настоящая сказочница", "День возвращенной книги".',
        eventCost: 'Бесплатно',
        eventImgSrc: require('../../assets/images/eventsImages/m-mai-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/m-mai-02.jpg'),
    },
]