export const eventsConfig = [
    {
        id: 98,
        eventDay: 'ВС',
        eventDayNumber: '19',
        eventInfoDate: '19 НОЯБРЯ',
        eventInfoTitle: 'Сказка о потеряном времени',
        eventDescription: '19 ноября в 12-00 часов приглашаем всех желающих на Сказку о потеряном времени"',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/1-1.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/v-2.jpg'),
    },
    {
        id: 99,
        eventDay: 'ПН',
        eventDayNumber: '04',
        eventInfoDate: '04 НОЯБРЯ',
        eventInfoTitle: 'Спектакль "Лавочка"',
        eventDescription: '04 ноября в 19-00 часов приглашаем всех желающих на спектакль "Лавочка"',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/L-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/L-02.jpg'),
    },
    {
        id: 100,
        eventDay: 'ПН',
        eventDayNumber: '04',
        eventInfoDate: '04 НОЯБРЯ',
        eventInfoTitle: 'Иллюзионное шоу',
        eventDescription: '04 ноября в 12-00 часов в Краснопахорском доме культуры "Звездный" впервые состоится иллюзионное шоу',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/Y-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/Y-02.jpg'),
    },
    {
        id: 101,
        eventDay: 'ВС',
        eventDayNumber: '29',
        eventInfoDate: '29 ОКТЯБРЯ',
        eventInfoTitle: 'Венок дружбы',
        eventDescription: '29 октября в 12-00 часов в Краснопахорском доме культуры состоится 9 межрегиональный фестиваль, посященный Международному дню толерантности ',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/2023-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/2023-02.jpg'),
    },
    {
        id: 102,
        eventDay: 'СР',
        eventDayNumber: '18',
        eventInfoDate: '18 ОКТЯБРЯ',
        eventInfoTitle: 'Встреча в клубе "Эрудит"',
        eventDescription: '18 октября в 16-00 часов в ДК "Звездный" состоится встреча на тему "Опасные игры и интернете"',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/I-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/I-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'ВТ',
        eventDayNumber: '17',
        eventInfoDate: '17 ОКТЯБРЯ',
        eventInfoTitle: 'Встреча с центром реабилитации бездомных животных',
        eventDescription: '17 октября в 18-00 часов в ДК "Звездный" состоится встреча с центром реабилитации бездомных животных',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/una-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/una-02.jpg'),
    },
    {
        id: 104,
        eventDay: 'ЧТ',
        eventDayNumber: '12',
        eventInfoDate: '12 ОКТЯБРЯ',
        eventInfoTitle: 'Встреча в клубе "Галактика"',
        eventDescription: '12 октября в 15-00 часов в ДК "Звездный" состоится встреча в клубе "Галактика" на тему "Угрозы глобальной сети"',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/internet-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/internet-02.jpg'),
    },
    {
        id: 105,
        eventDay: 'СР',
        eventDayNumber: '11',
        eventInfoDate: '11 ОКТЯБРЯ',
        eventInfoTitle: 'Встреча в клубе надежда',
        eventDescription: '11 октября в 16-00 часов в ДК "Юбилейный" состоится встреча в клубе здоровья и равных возможностей "Надежда"',
        eventCost: 'ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/O-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/O-02.jpg'),
    },
    {
        id: 106,
        eventDay: 'ВТ',
        eventDayNumber: '10',
        eventInfoDate: '10 ОКТЯБРЯ',
        eventInfoTitle: 'Игра',
        eventDescription: '10 октября в 17-00 часов в ДК "Звездный" состоится интеллектуальная игра в клубе "ЭРУДИТ"',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/K-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/K-02.jpg'),
    },
    {
        id: 107,
        eventDay: 'СБ',
        eventDayNumber: '07',
        eventInfoDate: '07 ОКТЯБРЯ',
        eventInfoTitle: 'Мастер-класс',
        eventDescription: '7 октября в 15-00 часов в ДК "Звездный" состоится мастер-класс ко Всемирному дню изготовления открытки',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/otk-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/otk-02.jpg'),
    },
    {
        id: 108,
        eventDay: 'СБ',
        eventDayNumber: '07',
        eventInfoDate: '07 ОКТЯБРЯ',
        eventInfoTitle: 'Мастер-класс',
        eventDescription: '7 октября в 12-00 часов в ДК "Юбилейный" состоится мастер-класс на тему "Открытка для бабушки"',
        eventCost: 'ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/otkritka-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/otkritka-02.jpg'),
    },
    {
        id: 109,
        eventDay: 'ЧТ',
        eventDayNumber: '05',
        eventInfoDate: '05 ОКТЯБРЯ',
        eventInfoTitle: 'Клуб сельчанка',
        eventDescription: '5 октября в 16-00 часов в ДК "Юбилейный" состоится тематическая встреча ко Дню старшего поколения"',
        eventCost: 'ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/S-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/S-02.jpg'),
    },
    {
        id: 110,
        eventDay: 'ВС',
        eventDayNumber: '01',
        eventInfoDate: '01 ОКТЯБРЯ',
        eventInfoTitle: 'Спектакль по произведениям А. Н. Островского',
        eventDescription: '1 октября в 18-00 часов в Краснопахорском доме культуры состоится спектакль ведущего творческого коллектива города Москвы  театра-студии "Мыслите"  (реж. Л. Герасимова).  Артисты представят постановку "Купеческая жизнь Замоскворечья", посвящённую 200-летию со дня рождения А. Н. Островского.  Вход свободный!',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/ostr-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/ostr-02.jpg'),
    },
    {
        id: 111,
        eventDay: 'ВС',
        eventDayNumber: '01',
        eventInfoDate: '01 октября',
        eventInfoTitle: 'Щелкунчик и кошки',
        eventDescription: 'Внимание! Внимание! Внимание!К нам едут кошки куклачева! В ДК "Звездный" 30 сентября в 12-00,ждем всех!! ',
        eventCost: 'ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/kotik-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/kotik-02.jpg'),
    },
    {
        id: 112,
        eventDay: 'СБ',
        eventDayNumber: '23',
        eventInfoDate: '23 сентября',
        eventInfoTitle: 'Круглый стол',
        eventDescription: '23 сентября в 17-00 состоится встреча "Многоликий мир" посвященный международному дню Мира',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/Mir-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/Mir-02.jpg'),
    },
    {
        id: 113,
        eventDay: 'СБ',
        eventDayNumber: '23',
        eventInfoDate: '23 сентября',
        eventInfoTitle: 'День села',
        eventDescription: 'Приглашаем 23 сентября в 12-00 всех на праздник старейшего села Былово.Вас ждут конкурсы,концертная программа, выставки, мастер-классы и много приятных сюрпризов',
        eventCost: 'ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/bulovo-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/bulovo-02.jpg'),
    },
    {
        id: 114,
        eventDay: 'ПТ',
        eventDayNumber: '22',
        eventInfoDate: '22 сентября',
        eventInfoTitle: 'Встреча в клубе "Лира"',
        eventDescription: '22 сентября в 18-00 состоится литературная встреча в клубе "Лира" приурочена к 140 летию Б.С. Жидкова, ждем заявки на участи до 24 сентября',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/lira-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/lira-02.jpg'),
    },
    {
        id: 115,
        eventDay: 'ВТ',
        eventDayNumber: '19',
        eventInfoDate: '19 сентября',
        eventInfoTitle: 'Мастер-класс',
        eventDescription: '19 сентября состоится мастер-класс в арт студии изобразительного искусства под названием "Придумай свой смайлик"',
        eventCost: 'ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/aut-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/aut-02.jpg'),
    },
    {
        id: 116,
        eventDay: 'ВТ',
        eventDayNumber: '19',
        eventInfoDate: '19 сентября',
        eventInfoTitle: 'Делаем поделку',
        eventDescription: '19 сентября в 17-00 делаем поделку ко Дню села из осенних цветов и листьев',
        eventCost: 'ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/sma-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/sma-02.jpg'),
    },
    {
        id: 117,
        eventDay: 'ВС',
        eventDayNumber: '24',
        eventInfoDate: '24 сентября',
        eventInfoTitle: 'Чтецкий фестиваль',
        eventDescription: '7 октября состоится чтецкий фестиваль, посвященный поэтам серебряного века, ждем заявки на участи до 24 сентября',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/silver-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/silver-02.jpg'),
    },
    {
        id: 118,
        eventDay: 'СБ',
        eventDayNumber: '16',
        eventInfoDate: '16 сентября',
        eventInfoTitle: 'Открытие мемориально-исторического парка',
        eventDescription: '16 сентября в деревне Софьино состоится открытие музея в мемориально-историческом парке «Редут 1812» Начало в 10:00. Вход свободный',
        eventCost: 'ПАРК РЕДУТ 1812 ГОДА',
        eventImgSrc: require('../../assets/images/eventsImages/redyt-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/redyt-02.jpg'),
    },
]