export const eventsConfig = [
    {
        id: 103,
        eventDay: 'ВС',
        eventDayNumber: '01',
        eventInfoDate: '01 ОКТЯБРЯ',
        eventInfoTitle: 'Спектакль по произведениям А. Н. Островского',
        eventDescription: '1 октября в 18 часов в Краснопахорском доме культуры состоится спектакль ведущего творческого коллектива города Москвы  театра-студии "Мыслите"  (реж. Л. Герасимова).  Артисты представят постановку "Купеческая жизнь Замоскворечья", посвящённую 200-летию со дня рождения А. Н. Островского.  Вход свободный!',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/ostr-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/ostr-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'ВС',
        eventDayNumber: '01',
        eventInfoDate: '01 октября',
        eventInfoTitle: 'Щелкунчик и кошки',
        eventDescription: 'Внимание! Внимание! Внимание!К нам едут кошки куклачева! В ДК "Звездный" 30 сентября в 12-00,ждем всех!! ',
        eventCost: 'ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/kotik-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/kotik-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'СБ',
        eventDayNumber: '23',
        eventInfoDate: '23 сентября',
        eventInfoTitle: 'Круглый стол',
        eventDescription: '23 сентября в 17-00 состоится встреча "Многоликий мир" посвященный международному дню Мира',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/Mir-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/Mir-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'СБ',
        eventDayNumber: '23',
        eventInfoDate: '23 сентября',
        eventInfoTitle: 'День села',
        eventDescription: 'Приглашаем 23 сентября в 12-00 всех на праздник старейшего села Былово.Вас ждут конкурсы,концертная программа, выставки, мастер-классы и много приятных сюрпризов',
        eventCost: 'ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/bulovo-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/bulovo-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'ПТ',
        eventDayNumber: '22',
        eventInfoDate: '22 сентября',
        eventInfoTitle: 'Встреча в клубе "Лира"',
        eventDescription: '22 сентября в 18-00 состоится литературная встреча в клубе "Лира" приурочена к 140 летию Б.С. Жидкова, ждем заявки на участи до 24 сентября',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/lira-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/lira-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'ВТ',
        eventDayNumber: '19',
        eventInfoDate: '19 сентября',
        eventInfoTitle: 'Мастер-класс',
        eventDescription: '19 сентября состоится мастер-класс в арт студии изобразительного искусства под названием "Придумай свой смайлик"',
        eventCost: 'ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/aut-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/aut-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'ВТ',
        eventDayNumber: '19',
        eventInfoDate: '19 сентября',
        eventInfoTitle: 'Делаем поделку',
        eventDescription: '19 сентября в 17-00 делаем поделку ко Дню села из осенних цветов и листьев',
        eventCost: 'ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/sma-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/sma-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'ВС',
        eventDayNumber: '24',
        eventInfoDate: '24 сентября',
        eventInfoTitle: 'Чтецкий фестиваль',
        eventDescription: '7 октября состоится чтецкий фестиваль, посвященный поэтам серебряного века, ждем заявки на участи до 24 сентября',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/silver-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/silver-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'СБ',
        eventDayNumber: '16',
        eventInfoDate: '16 сентября',
        eventInfoTitle: 'Открытие мемориально-исторического парка',
        eventDescription: '16 сентября в деревне Софьино состоится открытие музея в мемориально-историческом парке «Редут 1812» Начало в 10:00. Вход свободный',
        eventCost: 'ПАРК РЕДУТ 1812 ГОДА',
        eventImgSrc: require('../../assets/images/eventsImages/redyt-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/redyt-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'ЧТ',
        eventDayNumber: '14',
        eventInfoDate: '14 сентября',
        eventInfoTitle: 'Осенины',
        eventDescription: '14 сентября в 16 часов стреча в клубе "Горенка". Ирина Юрьевна подготовила для ребят множество творческих заданий.',
        eventCost: 'ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/ovoshi-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/ovoshi-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'ВТ',
        eventDayNumber: '05-11',
        eventInfoDate: '05-11 сентября',
        eventInfoTitle: 'Выставка работ участников кружков',
        eventDescription: 'С 05 ПО 11 СЕНТЯБРЯ в доме культуры "Звёздный" и его структурном подразделении в Былов, в ДК "Юбилейный", пройдет выставка работ участников кружков декоративно-прикладного творчества ко дню города',
        eventCost: 'ДК "Звездный", ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/Moscow-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/Moscow-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'CБ',
        eventDayNumber: '2',
        eventInfoDate: '2 сентября',
        eventInfoTitle: 'КиноЛекторий',
        eventDescription: 'В ДК "Звездный" 2 сентября в 12-00 состоится "Кинолекторий" ко дню солидарности в борьбе с терроризмом 19 лет со дня трагедии в Беслане',
        eventCost: 'ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/kinooo-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/kinooo-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'CБ',
        eventDayNumber: '26',
        eventInfoDate: '26 августа',
        eventInfoTitle: 'Игровая программа',
        eventDescription: 'В ДК "Юбилейный" 26 августа в Былово пройдет игровая программа "Первый раз в первый класс"',
        eventCost: 'ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/1k-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/1k-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'ПТ СБ ВС',
        eventDayNumber: '25 26 27',
        eventInfoDate: '25-26-27 августа',
        eventInfoTitle: 'Мастер-классы клубных формирований',
        eventDescription: 'В ДК "Звёздный" 26 и 27 в Былов, в ДК "Юбилейный", пройдут открытые уроки клубных формирований.',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/MK-zv-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/MK-zv-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'ПТ СБ ВС',
        eventDayNumber: '26 27',
        eventInfoDate: '26-27 августа',
        eventInfoTitle: 'Мастер-классы клубных формирований',
        eventDescription: 'В ДК "Звёздный" 26 и 27 в Былов, в ДК "Юбилейный", пройдут открытые уроки клубных формирований.',
        eventCost: 'ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/MK-bil-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/MK-bil-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'ПТ СБ ВС',
        eventDayNumber: '25 26 27',
        eventInfoDate: '25-26-27 августа',
        eventInfoTitle: 'День открытых дверей',
        eventDescription: '25, 26 и 27 августа в доме культуры "Звёздный" и его структурном подразделении в Былов, в ДК "Юбилейный", пройдут ДНИ ОТКРЫТЫХ ДВЕРЕЙ! На вопросы гостей ответят руководители клубных формирований. Вы сможете узнать, какие кружки и студии будут работать в новом творческом сезоне ДЛЯ ВАС И ВАШИХ ДЕТЕЙ! Приходите! Наши двери открыты!',
        eventCost: 'ДК "Звездный", ДК "Юбилейный"',
        eventImgSrc: require('../../assets/images/eventsImages/dod-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/dod-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'ВТ',
        eventDayNumber: '22',
        eventInfoDate: '22 августа',
        eventInfoTitle: 'Концертная программа',
        eventDescription: 'ДК "Звездный" 22 августа в 18-00 приглашает всех на концерт ко ДНЮ РОССИЙСКОГО ФЛАГА',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/F22-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/F22-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'ПТ',
        eventDayNumber: '18',
        eventInfoDate: '18 августа',
        eventInfoTitle: 'Выставка творческих работ',
        eventDescription: 'ДК "Звездный" 18-25 августа приглашает всех на Выставку творческих работ участников клуба "Радуга-Дуга" ко Дню Государственного флага',
        eventCost: 'ДК "Звездный"',
        eventImgSrc: require('../../assets/images/eventsImages/Ru-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/Ru-02.jpg'),
    },
    {
        id: 103,
        eventDay: 'СБ',
        eventDayNumber: '19',
        eventInfoDate: '19 августа',
        eventInfoTitle: 'Мастер-класс',
        eventDescription: 'В ДК "Юбилейный" 19 августа в 12-00 приглашает всех на мастер-класс от Татьяны Гаруфуллиной "Флаг России"',
        eventCost: 'ДК Юбилейный',
        eventImgSrc: require('../../assets/images/eventsImages/flag-01.jpg'),
        eventsPreviewImg: require('../../assets/images/eventsImages/eventsPreviewImgs/flag-02.jpg'),
    },
]